# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: speech.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'speech.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cspeech.proto\x12\x06speech\"\x1d\n\nAudioChunk\x12\x0f\n\x07samples\x18\x01 \x03(\x02\"\x1a\n\nTranscript\x12\x0c\n\x04text\x18\x01 \x01(\t2P\n\x0cSpeechToText\x12@\n\x12StreamingRecognize\x12\x12.speech.AudioChunk\x1a\x12.speech.Transcript(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'speech_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AUDIOCHUNK']._serialized_start=24
  _globals['_AUDIOCHUNK']._serialized_end=53
  _globals['_TRANSCRIPT']._serialized_start=55
  _globals['_TRANSCRIPT']._serialized_end=81
  _globals['_SPEECHTOTEXT']._serialized_start=83
  _globals['_SPEECHTOTEXT']._serialized_end=163
# @@protoc_insertion_point(module_scope)
